apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp-integration
  namespace: cp4i
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-cp-integration
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-cp-integration.v1.0.2
