apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscriptions.name }}
  annotations:
spec:
  {{- if .Values.subscriptions.channel }}
  channel: {{ .Values.subscriptions.channel }}
  installPlanApproval: Automatic
  name: {{ .Values.subscriptions.name }}
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  {{- else }}
  {{- toYaml .Values.subscriptions.subscription | nindent 2 }}
  {{- end }}