kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.hooktype }} 
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}
