apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Values.name }}-
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.hooktype }}
spec:
  template:
    spec:
      containers:
        - name: job
          image: {{ .Values.image }}:{{ .Values.tag }}
          command: [" {{ .Values.command}} "]
          args: 
          {{- toYaml .Values.args | nindent 12 }}          
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceaccount }}
  backoffLimit: 4