apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Values.name }}-
  annotations:
    argocd.argoproj.io/hook: {{ .Values.hooktype }}
spec:
  template:
    spec:
      containers:
        - name: job
          image: quay.io/openshift/origin-cli:latest
          command: ["oc"]
          args:
            - get
            - ingresses.config.openshift.io
            - clsuter
            - -o 
            - jsonpath='{.spec.domain}
      restartPolicy: Never
  backoffLimit: 4