kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.hooktype }}  
rules:
{{- toYaml .Values.roleaccess | nindent 2 }} 
