apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscriptions.platformnavigator.name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "200"
spec:
  {{- toYaml .Values.subscriptions.platformnavigator.subscription | nindent 2 }}
