# Default values for ibm-automation-foundation-core-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

subscriptions:
  ibmautomation:
    name: ibm-automation-foundation-core
    subscription:
      channel: v1.0
      config:
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 150m
            memory: 200Mi
      installPlanApproval: Automatic
      name: ibm-automation
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace
