apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mq-spring-app.fullname" . }}
  labels:
    {{- include "mq-spring-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mq-spring-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mq-spring-app.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mq-spring-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.http.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: QM
              valueFrom:
                configMapKeyRef:
                  key: QM
                  name: {{ include "mq-spring-app.fullname" . }}
            - name: CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: CHANNEL
                  name: {{ include "mq-spring-app.fullname" . }}
            - name: CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  key: CONNECTION_NAME
                  name: {{ include "mq-spring-app.fullname" . }}
            - name: USER
              valueFrom:
                secretKeyRef:
                  key: USER
                  name: {{ include "mq-spring-app.fullname" . }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: {{ include "mq-spring-app.fullname" . }}
            - name: QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: QUEUE_NAME
                  name: {{ include "mq-spring-app.fullname" . }}
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: {{ include "mq-spring-app.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
