apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "mq-spring-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.image.http.port }}
      targetPort: {{ .Values.image.http.port }}
      protocol: TCP
      name: 8080-tcp
    - name: 8443-tcp
      protocol: TCP
      port: {{ .Values.image.https.port }}
      targetPort: {{ .Values.image.https.port }}
    - name: 8778-tcp
      protocol: TCP
      port: {{ .Values.image.additional.port }}
      targetPort: {{ .Values.image.additional.port }}
  selector:
    {{- include "mq-spring-app.selectorLabels" . | nindent 4 }}
