apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscriptions.subscription.name }}
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    helm.sh/hook-weight: "100"  
spec:
  {{- toYaml .Values.subscriptions.subscription | nindent 2 }}
